### ISSUE TITLE
Outdoor air fraction and results

### ISSUE THREAD

**Issue by alago197** [kawesomekhan/covid-indoor#14]
Hi Kasim,

A doubt or question.  Just using the default values presented in the app, and only increasing the outdoor air fraction slider (from the 0 - closed room , to the right) is actually lowering (in the results pane) the maximum exposure time?

Regards,

Alvaro Fdez

**Comment by kawesomekhan** [comment]
Hi Alvaro,

Yes, this is correct! It might seem counterintuitive at first, but the logic is essentially this: 

The room has the main room in addition to a filtration system (assuming there is a filter, of course) that filters the recirculated air in the room. If the outdoor air fraction was 0, the whole room would just be recirculating the same air over, and over, and over again. If the outdoor air fraction was 1, there wouldn't be any recirculation - the air would simply come in, and go out. 

So, at lower outdoor air fractions, the filter ends up doing more work. This means there's a better chance that the infective aerosols will be filtered out of the air, which means that you can stay in the room for longer. Similarly, at higher outdoor air fractions, the filter does less work, so there's a better chance that the infective aerosols will remain in the room. 

If you'd like, I can provide a mathematical explanation (it just involves some algebra), but hopefully this makes sense.

-Kasim

**Comment by alago197** [comment]
Hi!

Many thanks for your explanations!. No, no need to delve in mathematical explanations (I did use also Martin's spreadsheet whch also contains them at the Instructions section).  I understood what you explained, yes.  I still don't fully understand the logic in the case there's no filter at all (or a lower quality, prefilter, unable to filter out effectively micron-size particles). At increasing ACHs (in this scenario, with no filter, or a poor performing filter) I thought that increasing the outdoor air fraction (so increasing the total flow rate) would have much more chance to dillute the infective aerosols, assuming of course there's present an exit or extraction system.

**Comment by kawesomekhan** [comment]
Great, glad this was helpful. In the case of no filter (or a poor filter), the logic is still the same. You're correct that increasing ACHs will increase exposure times. However, the ACH and outdoor air fraction are independent variables - increasing outdoor air fraction does not affect the ACH number. 

Happy to provide additional explanation if needed!

-Kasim

**Comment by kawesomekhan** [comment]
Hi Alvaro,

Turns out, you're definitely not the only person with this question. I'm currently working with Prof. Bazant and others to clear up this confusion for any users -- you'll see that I have renamed the outdoor air fraction slider to recirculation rate. It should be much clearer now that increasing the recirculation rate will increase filtration, thereby decreasing risk. More adjustments to come. 

-Kasim

**Comment by alago197** [comment]
Hi,
Yes, I did noticed. Well, another way would be making ACH instead a calculated value, asking the user for the supply airflow rate (Qs), the return airflow rate (Qr), and the desired outdoor air fraction (Qoa), mainly. Perhaps to be included in the Advanced section in your app?

I've already suggested to Martin that for example in NIST's FATIMA tool and paper there are some calculations (a derived ACH, from the parameters above that could be used (plus others as infiltration, exhaust airflow rate if present, and the presence of recirculation that you already provide).  Just for suggestion, if it helps, in https://pages.nist.gov/CONTAM-apps/webapps/FaTIMA/nano_10.js , in the computeSystem function, these calculations are available (and in the NIST paper itself).  

The thing is, given a fixed ACH as input or selected by the user, the rest of calculations (starting with the relaxation rate) for the guideline doesn't incorporate (or are influenced by) the outdoor air fraction, or even the total airflow rate (Q+Qf). 

My point doing this suggestion is that, as you can check if you try that NIST's tool (check the calculated airflows section), for a simple system with known supply & return airflow rates, higher outdoor air fractions can add to the ACH rate, so increasing the dillution of the infective particles present in the room, even without any extraction device (exhaust fans)
