### ISSUE TITLE
Risk Tolerance slider

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#21]
This slider seems over sensitive. I find the  "Safe" reduces times dramatically. The Labels themselves are a bit confusing (to me contact tracing is "safe".

**Comment by kawesomekhan** [comment]
Hi TheotherBiggles,

It would always be nice to have more control over the input, but I don't feel comfortable editing the risk tolerance slider as it stands - I would definitely like it to remain a slider (as opposed to numerical input) because the value is bound from 0 to 1. Decreasing the step size any further than 0.01 would make it difficult for the user to select precise values, which is necessary to produce replicable results. 

Could you explain a bit more on why the labels are confusing?

Kasim

**Comment by TheotherBiggles** [comment]
Dear Kasim,

I will be very happy to explain a bit more, but first just wanted to** 
congratulate you** on this very much needed online app.
I teach in a very large London University, and within my college “safe” room calculations I have witnessed 
being carried out are very crude - only measuring distance!

I was absolutely delighted when I came across your app and time permitting **anything I 
can do to help - I will.** :)

With regard to the Risk Tolerance slider I think there are several user 
interface problems with it (along with it seeming to alter the figures 
drastically).

I gather for it to work you need the steps to remain the same. If that 
is the case then I think both the slider and slider labelling needs to be far 
clearer.
Although TBH I think the slider should probably go into the advanced section as its effect is currently so strong.

The mask slider is pretty clear and if you don’t mind I would 
like to make some comparisons between the mask slider and Tolerance slider.

Title
The Title “Risk Tolerance” does not communicate as clearly in the same simple plain English way, that the slider above does with “Mask Fit/Compliance”. I think it could be a less ambiguous, or more focussed. Could you use “Risk Group Tolerance”?

Slider position convention:
The slider above for masks has the slider for Good *on the right*
The slider below for Tolerance, does not fit the convention you have 
established and puts (good) or low tolerance *on the left*
This reversal will confuse. I strongly suggest you keep all *positive 
settings to the right* throughout the app.

Labels/wording:
The wording above the slider is confusing as it is not reflected by the 
labels on the slider.

By default, the slider set to the vulnerable end of the scale, so I 
think you should *explain vulnerable first*.

Like this:
“More vulnerable populations such as the elderly or those with 
preexisting medical conditions will generally require a **lower risk 
tolerance**.
A **higher risk tolerance** will mean more expected transmissions during 
the expected occupancy period (see FAQ for details).”

The confusion on the slider label is that you have “0.01 contact 
tracing” and “1.0 unsafe” on the other- these labels require interpretation.

 I would keep convention order you established for mask slider and have labels that reflect the explanatory text like this:

On the left “High Risk - Unsafe” and on the right “Low Risk - 
Safe”. With the default position of the slider set to the right 0.01

There is no suggested reference point on the tolerance scale either 
(hence my comment on sensitivity). On the mask slider it is very clear, but on the tolerance slider, there 
is no scale label or suggestion of how relatively unsafe say a mid 
slider is.

I would not mention Contact tracing on the slider at all because country to country contact tracing seems to vary in effectiveness considerably. For instance in the UK our contact tracing system has been and largely is lamentably bad.

As a way to make the function of the slider less drastic I wonder if a (rather like masks) Risk Group drop down menu might be way to make this slider function a bit better?

**Comment by kawesomekhan** [comment]
Thanks for the input! 

There might have been a miscommunication regarding the risk tolerance title - the risk tolerance is indeed a risk tolerance and nothing more. It can apply to risk groups/groups of varying risk/vulnerability like you said, but it is more or less an arbitrary value depending on how safe the user wants their room to be. 

I will consider moving it to the Advanced section - but it is a major component of the safety guideline so I wouldn't want to hide it too much. 

I understand your point about having "good" being on the right and "bad" on the left. However, for sliders in many applications (number lines, temperature, rulers), the convention is larger values on the right and smaller values on the left, which inclines me to keep the order as is. 

I like your comment regarding the description wording - I think switching the order will be better. 

I also agree that there could be more reference points within the slider itself, and that the "contact tracing" and "unsafe" could be altered.

We've actually just started working on translating the app into multiple languages, so I will have to run these changes by Bazant and Bush to make sure we're on the same page before I can implement them. 

-Kasim

**Comment by TheotherBiggles** [comment]
Yes larger values on the right is a software convention or programming convention but not a *intuitive* or helpful one. If  it remains it inevitably give a contradictory affordance.

For instance, in the real world is taps are turned on when turned left/anti clockwise (as a result of their original screw mechanism), the later invention and use of rheostat based control (as in volume control) will  turn to the right to make them louder. This is a physical contradictory affordance, that has caused confusion ever since.

If you swap good bad values left and right within the app, you are effectively introducing a contradictory affordance for the user. I would avoid doing that if possible - particularly if the only reason is an arbitrary software convention.

**Comment by kawesomekhan** [comment]
There might have been a miscommunication - larger values on the right might be a software/programming convention, but more importantly it is what the user expects when using an app/website. This intuition stems from the real-world examples of number lines, rulers, and horizontal bar charts. In any case, even if I were to reverse the slider values, I would be still contradictory with the mask slider by having values decrease to the left.

We're currently going through some text revisions before we translate so these comments come at an apt time - many of your suggestions have been helpful and I've begun to incorporate them on our end. You may be able to expect some updates by next week!

-Kasim

**Comment by kawesomekhan** [comment]
Text has been finalized and published
