### ISSUE TITLE
Mask vs. No Masks

### ISSUE THREAD

**Issue by kawesomekhan** [kawesomekhan/covid-indoor#22]
Add potential plot/comparison

**Comment by TheotherBiggles** [comment]
Having cotton+chiffon, seems an odd dropdown for the highest grade choice of mask, surely it is more a face covering than mask. 

I hope I am not I am being too Eurocentric but here we commonly use FFP standards for a tested standard of mask.
FFP3 being the highest (effective filter for aerosol covid frequently used in hospitals, but becoming more popular with public especially in enclosed spaces), FFP1 Lowest (DIY dust mask). 

Would it not be a good idea to have these and their N equivalents on the list?

**Comment by kawesomekhan** [comment]
May end up cluttering the UI - doesn't seem necessary anymore given current functionality
