### ISSUE TITLE
Use Colours to reinforce risk

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#25]
The colours used throughout are mainly Black, Red or Light Blue.
If possible, a traffic light system of colours would be visually much clearer.

Red: Bad/poor
Orange :Medium
Green: Good Desirable
Blue: Further information links

Reserve Black for text

This colours would work for all  of your sliders and drop down menus. Below is an example from the British Medical Journal.
The chart boils down the complex into an understandable simple matrix in simple traffic light manner.
Fig.3 of this article: https://www.bmj.com/content/370/bmj.m3223

So for sliders have green for "good" options, red "bad" etc
Drop down menus ie for ventilation None=red, open windows = orange, Hepa filtered strong mechanical = Green
Masks - Quilters Cotton=red to FFP3 mask green
Fit compliance None 0%= Red Poor 50%=orange 95% Good=Green
Expiratory Activity. Breathing fast deep breath= Red  Talking Loud= Orange Calm Nose Breathing = Green 

This could also make your summation page clearer - the max good duration/occupancy times being in green. The bottom figure for room occupation worked out for comparison would deserve to be red.

**Comment by kawesomekhan** [comment]
I'm always a fan of color - but I think adding traffic light coloring to all the app dropdowns and elements will be rather distracting and perhaps reveal a too-high density of information, which might deter some members of the general public (a key audience) from playing with the app. Plus, traffic light coloring tends to be unfriendly towards people with colorblindness. I think it is better for users to ease themselves into it by testing out different inputs and seeing how the outputs are affected, and draw their own conclusions from there.

**Comment by TheotherBiggles** [comment]
Yes I agree with drop downs it could be an issue *if the drop down values are not grouped *- ie red, green, green, amber, red etc would indeed be horrible and confusing. 

I was thinking of them being grouped, ie no ventilation red, window open orange, efficient filtered air change green.
BTW it would indicate that some parameters that *seem innocent* are not, like low ceiling height. 

There are so many parameters that a person just playing will have to spend a lot of time doing that before they figure out what is wrong - why make it hard?

I still feel colours would be clear if they are grouped. The traffic light system is used and standard in the Mac operating system and countless other apps.

Re Colour Blind.
Just to be clear I was suggesting this change for *the colour of your type*.
It definitely could be an issue if you made the *background* a strong colour with black type on it, less so with white type. 

However for common Dueteranomly Green/Red will seen as brown/black/dark grey. Orange mid brown/dark grey/grey. This is only an issue if you have to be able to choose actions based on colour alone (as say with wiring a plug).

If Colour blindness is a major concern, then I would suggest changing the light blue to a slightly darker hue than you currently have - that will turn light grey.
