### ISSUE TITLE
Expiratory Activity:

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#26]
Although "Expiratory Activity" is technically correct is it clear for the common user?
Could this be renamed Type of breathing? Or maybe Breathing activity?
To clearly focus the user on the importance of recognising the type of breath.

The list itself also seems to have got a bit cluttered and over complicated.
For instance what is nose - nose? and alternative option Deep fast? and Fast deep?

Again for simplicity, I would limit the list to what is recognised as less likely to transmit to most likely to transmit aerosol covid as simply as possible, with a bracketed examples so for instance from:
Quiet Breathing (as when reading)
Moderate Breathing (as when talking)
Strong breathing (as when singing)

To a maximum of around 7-9 types (because longer list are less likely to be used)

**Comment by kawesomekhan** [comment]
I agree this section can be clarified!

As stated in my risk tolerance response, I'll have to check with Bazant and Bush.

**Comment by kawesomekhan** [comment]
Text has been finalized and published
