### ISSUE TITLE
FAQs section

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#27]
I would be careful this section seems geared to the specialist scientific reader. With little practical advice.
At the moment the FAQ section does not seem to fit the need for simple explanation to translate a complex problem.

Starting with "I know my  ACH/MERV numbers. Where can I enter them?" to me at least does not sound like a very frequent FAQ : )

But the explanation of what is not accounted for does seem more appropriate.
I suggest start simple then get technical. By all means point to advanced section but later in the FAQs

Would some questions like below help explain the reason and purpose of the app better?:
Why does the height of the room matter?
I am spaced 2m apart why is that not enough?
Does still air in a room effect transmission?

**Comment by kawesomekhan** [comment]
Good idea! It turns out that we had been getting very scientific questions on our end, but I'm sure there are questions that go unreported, much like the ones you've suggested. 

As stated in my risk tolerance response, I'll check with Bazant and Bush before modifying the text.

**Comment by kawesomekhan** [comment]
Text has been finalized and published
