### ISSUE TITLE
Recirculation rate clarification

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#32]
Could this have additional descriptors?

In basic mode I am not sure everyone will understand how recirculation happens.
None is clear (no recirculation) but...

what would a typical "slow" recirculation situation be? An example beside it would help.
For instance linking to your ventilation methods - so would on average an open window give a "moderate" score?
Distinguishing between non recycling mechanical ventilation and recycled air ventilation is not very clear here.

**Comment by kawesomekhan** [comment]
I agree, it would be better to change "slow/moderate/fast" to something more descriptive if possible. I'll discuss this with Martin & John.
