### ISSUE TITLE
Copy link with all parameters in URL or hash

### ISSUE THREAD

**Issue by jcmaslan** [kawesomekhan/covid-indoor#41]
I wanted to send our office space as a link to teammates and it would be great to copy a fully specified URL that includes all the parameters I had specified.

**Comment by kawesomekhan** [comment]
Hi Carter,

This is definitely a good feature to have. We're currently working on bringing an updated Advanced mode with some alternative risk scenarios - once that's pushed (hopefully soon) this will be next in the pipeline. 

-Kasim

**Comment by kawesomekhan** [comment]
Functionality accomplished via Excel importing feature
