### ISSUE TITLE
Add a "number of events" input

### ISSUE THREAD

**Issue by greggman** [kawesomekhan/covid-indoor#42]
In other words, let's say it says it claims it's "safe" to be in a restaurant with 10 people, no masks (because we're eating), 
Currently that says 2 hours. So based on that I decide to go to a restaurant 3 times a day, 7 days a week, every week. AFAICT there is no way to show what my risk goes up doing something multiple times.

To put it another way it says 10 people for 2 hours no masks is ok. Some people will take that as it's okay to stay in the same room with 10 others as long as they step outside for 30 seconds every 2 hours. Isn't going to a restaurant with 10 unmasked people for 2hrs a day for 7 days the same as going to a restaurant with 10 unmasked people for 14hrs once? Or maybe another way to put it, how long between events until this recommendation "resets".

 It would seem useful to add "how often do you expect to do this"

**Comment by kawesomekhan** [comment]
Hi Greggman,

This is something we've been discussing over the past few months and whether we should add it. You're correct in that this is reporting the cumulative exposure time - so if the app reports the room should be limited to 14 hours total, this could be 2 hours over 7 days, or 2 days for 7 hours, or 14 hours continuously, etc. 

When analyzing a scenario like going to a restaurant for 2 hours every day, we then have to consider things like testing frequency or days to removal, assuming that any individuals who have been infected with COVID-19 will eventually get tested and maintain social isolation. Additionally an assumption might have to be made where, in the case of a restaurant being open for 8-12 hours/day, any infectious air would be removed overnight. As these times get longer and approach 24 hours/day, this assumption would no longer be true.

I'll revisit this with Martin & John and see if how we'd like to implement/acknowledge this. But for the most part, it should be reasonable to divide the total exposure time by the time people spend in that room per day to get an estimate of how many days that activity can take place. Once that number approaches 7-14 days it might be safe indefinitely (but I need to confirm this with Martin & John).

-Kasim
