### ISSUE TITLE
Define "safe"

### ISSUE THREAD

**Issue by Adamantish** [kawesomekhan/covid-indoor#43]
This is the most important value in the model that should be surfaced.

I'm happy to take a 1% chance of getting infected. That would be much too high for my mother in law with a respiratory condition and immune deficiency. So what's the safe level for her to attend? What's the safe level for me to attend if I'm seeing my mother in law 3 days later?
Maybe we consider 0.5% safe for us attendees but repeating that gamble over 30 million family get-togethers might not be good enough to be safe for containment at the national level. 

Let's make this stuff clearer or express the risk in relative terms visually so different activities are easy to compare.

**Comment by kawesomekhan** [comment]
Hi Adam,

Yes, the risk tolerance is an extremely important parameter in the safety guideline. To provide some context, values for Cq (the infectiousness of exhaled air) were parametrized based on the Skagit County choir transmission incident, where 1 symptomatic individual transmitted COVID-19 to 87% of the group, resulting in 3 hospitalizations and 2 deaths. As a result, the model is erring on the side of caution - the "typical" COVID-19 patient may have a lower average Cq, which would allow for increased exposure times.

The risk tolerance is also a limit on what is defined as the "Indoor reproductive number" R_in (which is discussed in the paper in further detail). This is analogous to the basic reproductive number R_o. Much like how R_o needs to be < 1 to curb the spread of the pandmic, R_in is also set to be < 1 to curb the transmission of COVID-19 within indoor spaces. So if this model was indeed adhered to over 30 million family get-togethers with a risk tolerance = R_in = 0.1, transmission would be contained at the national level.

It is also worth mentioning again that this is assuming at least one infected individual is in the room. So depending on the prevalence of COVID-19 within the local population, these limits on time could actually be extended if the prevalence is low (we're currently working on releasing an updated Advanced mode with these alternative risk scenarios).

In the end, however, risk tolerance is going to be affected by how safe you feel, and it's impossible to limit COVID-19 transmission to 0.00...%. We are working on making some language updates, so keep an eye out for an update soon. If you would like to experiment with risk tolerance values below 0.01, you can feel free to use the spreadsheet version (http://web.mit.edu/bazant/www/COVID-19/).

-Kasim
