### ISSUE TITLE
Modeling environments where only part of the people are using masks 

### ISSUE THREAD

**Issue by erickcampos50** [kawesomekhan/covid-indoor#72]
Hello. This is a great tool and I would like to be able to use it to model health care environments where part of the people are using masks (doctors, nurses, etc) and part are not (patients).

Could you create an advanced II section where we could set the parameters in two sections and see the results?

**Comment by kawesomekhan** [comment]
Hi! I am glad you find the tool useful. You can account for this using the mask fit/compliance slider, which captures both the fit of the mask as well as what percentage of people are wearing masks (I.e. compliance). 

-Kasim

**Comment by erickcampos50** [comment]
Thank you for this quick response.

So, if I have a room with 10 people and only 3 of them are using N95 masks,
if I set mask fit to 30% I'll be able to calculate the time limit for all
of them, right?

But how can I setup the different activities they're doing and the
respective risk/time limit of exposure of the two groups? Is there a way to
get that?

In our scenario we have masked people releasing and inhaling different
amount of virus from unmasked group, but with them all sharing the same
room I would like to evaluate how it would impact each group separately. Is
this possible?





Em sáb, 14 de ago de 2021 15:40, kawesomekhan ***@***.***>
escreveu:

**Comment by erickcampos50** [comment]
By the way, I know a little bit of python. So if there is a trivial way to
achieve that by direct using of the code I could try.

Em sáb, 14 de ago de 2021 17:23, Erick Carvalho Campos <
***@***.***> escreveu:

**Comment by kawesomekhan** [comment]
Hi Erick,

Apologies for the delay in responding - this completely slipped by me. To answer your questions:

> So, if I have a room with 10 people and only 3 of them are using N95 masks,
> if I set mask fit to 30% I'll be able to calculate the time limit for all
> of them, right? 

Correct.

> But how can I setup the different activities they're doing and the
> respective risk/time limit of exposure of the two groups? Is there a way to
> get that?

If you'd like to model a set of different activities occurring in the same place (talking, singing, etc.), I think it makes most sense to use the Excel spreadsheet. I believe the workaround here would be to use a Cq value that would be an time-weighted average of the various activities involved. If this doesn't make sense let me know and I can elaborate!

> In our scenario we have masked people releasing and inhaling different
> amount of virus from unmasked group, but with them all sharing the same
> room I would like to evaluate how it would impact each group separately. Is
> this possible?

When you say "releasing and inhaling different amounts of virus from unmasked group" - I'm not sure if this would be consistent with the well-mixed assumption of the model. Could you elaborate the thought process here? 

-Kasim

**Comment by erickcampos50** [comment]
Hello!

Apologies for the delay in responding - this completely slipped by me.

No problem, I'm grateful to count on your help anyway.

If you'd like to model a set of different activities occurring in the same
place (talking, singing, etc.), I think it makes most sense to use the
Excel spreadsheet. I believe the workaround here would be to use a Cq value
that would be an time-weighted average of the various activities involved.
If this doesn't make sense let me know and I can elaborate!

Do you have a spreadsheet with that functions implemented? It would be
great, because I can understand spreadsheets better than Python coding.


When you say "releasing and inhaling different amounts of virus from
unmasked group" - I'm not sure if this would be consistent with the
well-mixed assumption of the model. Could you elaborate the thought process
here?

We wanted to understand and manage the risks in dentistry clinics and other
health clinics where normally we have patients and attendants doing
different activities and using different kinds of masks (or no masks at all
in the case of dentistry patients).

For instance: as patients remain seated, attendants (doctors, dentistries,
nurses, and others) have moderated activities in the same room. So they
will have different respiratory activities.

Our main goal is to be able to model and plan actions to reduce risks
considering the specific risks of each of the groups that interact in this
scenario. To accomplish that, what we look for is ways to partition groups
characteristics when using your great tools.

Right now we are talking about health spaces, but this group
segregation/partition could also be useful when planning classrooms
mitigation measures.

Best regards







Em qui., 30 de set. de 2021 às 19:06, kawesomekhan ***@***.***>
escreveu:

**Comment by kawesomekhan** [comment]
> Do you have a spreadsheet with that functions implemented? It would be
> great, because I can understand spreadsheets better than Python coding.

Sure! If you visit the link at the top of the app (http://web.mit.edu/bazant/www/COVID-19/) you will find the download for the Excel spreadsheet.

And thank you for the explanation! I now have a better idea of what you are trying to model. I think the spreadsheet is still the best way to go here, given the differences in activities/mask wearing/etc. If you have questions on how to obtain the right values in the spreadsheet, let me know. 

-Kasim Khan

**Comment by erickcampos50** [comment]
Thanks!!

Em ter, 5 de out de 2021 10:13, kawesomekhan ***@***.***>
escreveu:
