### ISSUE TITLE
possible mistake spotted

### ISSUE THREAD

**Issue by sebtix** [kawesomekhan/covid-indoor#76]
Hello
I see that this (excellent) Github project is still alive, and I'm very pleased to see that !
I've n ever used Git though, but wanted to raise your attention on a possible point of concern.
Below is the "copy/paste" (without the images of the formulas) of my email to Mr. Bazant, sent on June 15 2021 (never answered, probably was marked as spam or unread) : 

-----------------------------------------------------------------
Hello,

I have read your paper “Monitoring carbon dioxide to quantify the risk of indoor airborne transmission of COVID-19”, and I’ve used the related tools that you have provided with great interest. Thank you for such great work!
Even though I’m not an airborne scientist of any sort (I’m simply an engineer working in IT), I wanted to draw your attention to a specific aspect of the tools (both the Excel sheet and the online app) that looks weird to me :

Let’s assume the following conditions (for example) :
- Risk tolerance left at default value : 0.1
- Exposure time : 4 h
- Volume of the room : 60 m3
- Outdoor air exchange rate : 2.5 /h
- Recirculation air exchange rate : 0
- Men breathing flow rate : 0.5 m3/h
- Infectiousness of exhaled air : 40 quanta/m3
- Age group : 0.68
- Variant : 1.58
- Mask aerosol passage probability : 0.5
- all other parameters left at their default values

Then the Excel sheet and the online tool will provide the following results:
- Maximum safe occupancy : 3 persons
- Safe CO2 concentration (delta with background CO2 concentration) : 656 - 410 = 246 ppm

Now what I did was to use equation (10) of your paper to compute the approximate CO2 concentration one could expect from these 3 persons in this room. Using the same figures as above, this gives an expected CO2 concentration of  342 ppm … which is above the limit provided by the tools (246 ppm) !
… which does not seem consistent: how could the room be safe for 3 persons, if these persons generate a CO2 concentration above the “safe CO2 concentration” ?

So I’ve looked into the Excel sheet and your paper in closer details, and I believe I might have identified the cause for the discrepancy:
Your equation (22) introduces a ratio N / Nt:
However, in your Excel sheet (and apparently in the online tool as well), the cell “C74” does not have this ratio.
Indeed, instead of using the formula obtained from equation (22) above from your paper, the tool and Excel sheet use a similar formula, but with the last fraction missing

While this is not such of a big deal when the considered number N of persons is important (N / (N - 1) ~= 1 when N tends to infinite), this can dramatically change the result when the number N of persons is small.
The most extreme case is when N = 2, where the fraction changes the result by a factor 2. In my example above, N=3, so the impact is pretty high too.

If I introduce this fraction in your Excel sheet, then the results no longer seem inconsistent. For my example above :
- Maximum safe occupancy : 3 persons
- “New” safe CO2 concentration (delta with background CO2 concentration): 779 - 410 = 359 ppm  
… which is just above than the 342 ppm generation of CO2 by these 3 persons.

Sorry for the long email, and I hope I did not waste your precious time :)
Anyway, thanks a lot for the great paper and tools, they are of precious help and interest.
Best regards,
-----------------------------------------------------------------

So according to me, there is an error in the results shown in the tool , which impacts the results shown in the tab "Calculate Safe CO₂ Concentration"

Both results displayed in:
"the calculated safe time-averaged CO₂ concentration in this space is XXX ppm"
"the guideline would be violated after XXX hours"
should be multiplied by (N / (N-1)) where N is the number of persons in the room entered by the user.

Hope that helps, and thank you again for the great work

**Comment by kawesomekhan** [comment]
Hi sebtix,

Apologies - this slipped by me! Thank you for bringing this to my attention. I'll will investigate this and keep you in the loop. 

-Kasim Khan

**Comment by kawesomekhan** [comment]
Hi sebtix, it looks like there is indeed a discrepancy between the calculation you're doing and what is occurring in the spreadsheet and app. Not to worry, though - this is because we are making the conservative assumption of N / Nt = 1 (see the paragraph towards the bottom of page 5 in the paper), which accounts for "the early to middle stages of an
epidemic or when p_i and p_im are not known." In the other risk modes where prevalence (p_i) is known, we do not make this assumption and instead incorporate N / Nt into the calculation like you're describing.
