### ISSUE TITLE
Heroku is closing all free plans

### ISSUE THREAD

**Issue by quinncomendant** [kawesomekhan/covid-indoor#83]
Heroku will [no longer offer free hosting](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq):

> “… free dynos will be scaled down to 0 and hobby-dev databases will be deleted starting November 28, 2022.”

Is there a plan to pay to keep the [COVID-19 Indoor Safety application](https://indoor-covid-safety.herokuapp.com) online, or move it to a different free service (such as [GCP Cloud Run](https://cloud.google.com/run), [Render](https://render.com/), [Fly](https://fly.io/), or [Railway](https://railway.app/))?

**Comment by jlrjackson** [comment]
I'm also interested to know whether the site will continue to be up or if it will be moved or mirrored somewhere else?  I would be happy to contribute to a ko-fi or Patreon or such for hosting costs, since this is a useful tool.

**Comment by kawesomekhan** [comment]
Hey! Terribly sorry for the late reply but I've been using a paid dyno for the past couple of years. Some of that has been funded especially when the website was receiving a fair bit of media attention, but more recently I've scaled down and have been paying out of pocket.

@jlrjackson very kind of you to offer the support! A ko-fi/Patreon aren't things I've considered but I suppose it can't hurt to include somewhere. 

I hope to keep this site running indefinitely. I don't foresee any issues except for the one item I do need to take care of, which is to upgrade from the Heroku-18 stack (currently deprecated and will reach end of life in April 2023). Hopefully I'll have some this weekend to take care of that. 

Kasim
